### ISSUE TITLE
could we make morph retrieval an optional parameter?

### ISSUE THREAD

**Issue by balmas** [perseids-publications/treebank-template#25]
For purposes of publication of trees, there isn't really any value in doing the retrieval from the morphology service, and it just adds alot of unnecessary service calls.

It can be disabled by setting `noRetrieval: "online"` in the morph plugin configuration.  Could we make it possible for the treebank-template to have this set it its config.json file (and thus carried over to ArethusaConfig.js) so that users of the template can decide whether they want it or not?  (I don't really know if there is ever a reason it would be desirable but don't know if we want to rule that out).

**Comment by zfletch** [comment]
That's a great idea. Combined with https://github.com/alpheios-project/arethusa/pull/803 and https://github.com/perseids-publications/treebank-template/pull/9 it would mean that the Treebank Template is entirely self contained.

I think that we can just do the simplest thing and add `noRetrieval: "online"` to the config. If there is someone who needs that functionality, we can always add the option later.

**Comment by zfletch** [comment]
Addressed in https://github.com/perseids-publications/treebank-template/pull/28
