### ISSUE TITLE
In some cases, Edge does not display "Credits" correctly for embedded treebanks

### ISSUE THREAD

**Issue by zfletch** [perseids-publications/treebank-template#43]
In certain cases, the "Credits and more information" link in the embedded treebanks page, when used as part of the Alpheios integration, does not display correctly on MS Edge (thanks to @rgorman for finding the bug):

![edge](https://user-images.githubusercontent.com/3039310/86020538-08442b00-b9f6-11ea-8690-861ccc83b778.png)

**Comment by balmas** [comment]
not sure yet if this is an Alpheios or Treebank tremplate issue ... I entered a bug in Alpheios for it too: alpheios-project/alpheios-core#476

**Comment by zfletch** [comment]
I haven't been able to reproduce the position of the "Credits and more information" link, but I have been able to replicate at least part of this bug. Unfortunately, it isn't limited to Edge. Fortunately, it only happens when a user changes the window size: when the window starts with a smaller height and then the user increases the height, the `main-body` div increases in size but the background `canvas` div does not also expand. The bug also happens when the window's height is decreased but the results look a little different.

---

MS Edge:

<img width="572" alt="edge" src="https://user-images.githubusercontent.com/3039310/88334178-60253780-ccff-11ea-8e76-d4130a158cf6.png">

---

Firefox (macOS):

<img width="1070" alt="ff" src="https://user-images.githubusercontent.com/3039310/88334528-eccff580-ccff-11ea-9f32-b165e5bd68cd.png">

---

Reverse (starting with a tall window) (macOS):

<img width="1040" alt="ff-reverse" src="https://user-images.githubusercontent.com/3039310/88334541-f0fc1300-ccff-11ea-8a3e-3c78fa42c277.png">


I went back to the commit that first introduced the `/embed/` functionality and it's always been broken, but it was broken differently prior to https://github.com/perseids-publications/treebank-template/pull/29. Before that PR, it looked like this:

<img width="450" alt="oldest" src="https://user-images.githubusercontent.com/3039310/88335120-c9597a80-cd00-11ea-862c-a295cb61f8bf.png">


I think the change may be related to automatic resizing in Arethusa. Even though the newer bug looks worse (IMO) than the older one, I think it's actually closer to to the correct behavior. The `main-body` div is now resizing correctly, while it wasn't before. The only problem is that the `canvas` is not div is not also resizing.

**Comment by balmas** [comment]
could we fix that by updating the canvas size in Arethusa during resizing?

**Comment by zfletch** [comment]
I think that would work.

**Comment by zfletch** [comment]
This shouldn't be an issue since https://github.com/perseids-publications/treebank-template/pull/74 was merged.
