### ISSUE TITLE
add update instructions to getting started

### ISSUE THREAD

**Issue by balmas** [perseids-publications/treebank-template#44]
requested by @nevenjovanovic:

one thing bothers me about the current treebank templates and their Git
workflow. What happens if I have forked the repo, adapted the
configuration and added my documents -- and then you make a change to the
upstream repository, and I want to update my forked one?

In other words, are we, after the fork, committed to the forked version,
and we have to do everything again if the upstream repository is updated?
And what would be the best workflow for this "do everything again"?

Maybe, for advanced users who want to keep up with your work on the upstream repository, another workflow could
be developed and described?

**Comment by zfletch** [comment]
The instructions in the README for updating are currently:

* `git pull source master`
* Fix merge conflicts
* `git push origin master`

When we add update instructions to the getting started document, we should probably specify a set of commands that will keep the user's `src/config.json` but uses the source branch's version for everything else.

**Comment by balmas** [comment]
agreed. I'm not sure myself of what those steps are ...
