### ISSUE TITLE
Question: what do I need to have installed to try out the templates?

### ISSUE THREAD

**Issue by nevenjovanovic** [perseids-publications/treebank-template#5]
@zfletch -- could you explain what do I need to install (beside yarn https://yarnpkg.com/lang/en/)? How do I publish to my github pages -- do I clone the repo and create an appropriate github.io domain, or else...?

**Comment by nevenjovanovic** [comment]
I see now that the github configuration is done in `package.json` and `src/config.json`.

**Comment by zfletch** [comment]
There are a few steps involved in getting own repository set up for the first time, but once you have it set up, it should be easy to make updates.

1. Create a new project in GitHub.
2. Clone `perseids-publications/treebank-template`
3. Change `origin` in the cloned repository to the new project you created in GitHub
4. Install NodeJS and Yarn and then run `yarn install` in the repository
5. You should now be able to test the application by running `yarn start`
6. Update the `"name"` and `"homepage"` fields in `package.json`. The `"homepage"` field should be the GitHub Pages URL associated with the repository. For example, if your new repository is `nevenjovanovic/my-treebanks`, the `"homepage"` would be `"https://nevenjovanovic.github.io/my-treebanks/"`
7. Replace the XML files in `public/xml` with your own XML files
8. Likewise, update `src/config.json` to refer to the new files. I think the format of the JSON is mostly self-explanatory, but if you have difficulty, let me know and I will do my best to help
9. Run `yarn deploy` in the repository and then on GitHub visit "settings" and turn GitHub pages on. The source should be "gh-pages branch"

If you follow these steps and find a problem, then let me know.

Also I should mention that I can set up a new repository for you within https://github.com/perseids-publications/ and give you edit access if you would prefer that.

**Comment by nevenjovanovic** [comment]
Yup, followed the steps and everything works now at https://nevenjovanovic.github.io/grp-grc-treebanks/ -- thanks, @zfletch

**Comment by zfletch** [comment]
That's great!
