### ISSUE TITLE
Allow publications to be hidden

### ISSUE THREAD

**Issue by zfletch** [perseids-publications/treebank-template#69]
Currently, when publications have multiple sections, each section is displayed on the index page. There should be a way to configure a publication so that there is only one link, and that goes to the publication page (e.g. [https://perseids-publications.github.io/treebank-template/on-the-crown](https://perseids-publications.github.io/treebank-template/on-the-crown)).

This would allow large collections of treebanks to be displayed more easily.

**Comment by balmas** [comment]
Related to this, it would be nice to be able to have publications that are accessible but not listed publicly at all.
