### ISSUE TITLE
Webpage not generated by cloned template

### ISSUE THREAD

**Issue by rgorman** [perseids-publications/treebank-template#75]
I have cloned this the template using instructions at https://perseids-publications.github.io/treebank-template/instructions/getting-started/

No webpage appears at https://rgorman.github.io/ugrad-research-trees/

**Comment by zfletch** [comment]
I cloned your repository and it built correctly. See https://zfletch.github.io/ugrad-research-trees/. It's possible there was a minor GitHub outage. Have you tried running the action again?
